language: cpp
os: windows
env:
 - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
install:
 - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
script: 
 - export PATH=$MSBUILD_PATH:$PATH
 - mkdir build && cd build
 - cmake ..
 - cmake --build . --config Release
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: 'C:\Users\travis\build\jmskmz\NoVmp\build\NoVmp\Release\NoVmp.exe'
  skip_cleanup: true
  on:
    tags: true
